[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
altrepolib = { path = "../altrepolib" }
anyhow = "1.0.100"
serde_json = "1.0.147"
tokio = { version = "1.48.0", features = ["full"] }
